project_id = "rdxaqiacoitzeowehdts"

[functions.chat]
verify_jwt = false

[functions.agent]
verify_jwt = false

[functions.create-api-key]
verify_jwt = false

[functions.v1-messages]
verify_jwt = false

[functions.redeem-code]
verify_jwt = false
